feat: Update ecommerce
mparticle-integrations/mparticle-javascript-integration-amplitude pull request #45
Opened 2022-08-24 03:00 UTC by rmi22186

## Summary

@alexs-mparticle - The below is quite confusing and we should do a quick chat over zoom. I am summarizing as best I can for posterity. This [Google Sheet](https://docs.google.com/spreadsheets/d/1m_nhSW5_lsxg5k47MX_B9HJPEFeVrQ0UL4QrMLft_c4/edit#gid=1656373099) was created by Amplitude to show the current behavior and the desired behavior.  Given this PR is for web, you should only look at client side behavior.

Currently, our Amplitude ecommerce mappings work as follows using our internal `expandCommerceEvent` method from the core SDK: 
1. **Revenue events:** (ie. a `Purchase` or a `Refund` including 2 products)
a.   expand the event to be 3 events - 1 purchase/refund summary event that uses the amplitude.logRevenueV2 method which results in an `Amplitude Revenue` event, and 2 `eCommerce - purchase - Item` events, one for each product

2. **Non-revenue events** (ie. `AddToCart` including 2 products)
a. expand the event to be 2 items - 2 `eCommerce - add_to_cart - Item` events, one for each product

Amplitude wants us to make a change where we have "summary events", and an option to either include or exclude the individual item events.  Due to backwards compatibility issues with our server team and customer requests, the flag will be called `excludeIndividualProductEvents` (boolean).  All summary events will include a `products` key with a JSON of the products.

We need to support 2 scenarios:
A. scenario A - only a summary event is sent
B. scenario B - To maintain backwards compatibility send a summary event **as well as** the previously sent events, (the item level events and a revenue event if it's a purchase/refund event)

Amplitude's server has special behavior for revenue events, and reads keys prefixed with `$`.  These are called reserved attributes and help Amplitude calculate things like customer LTV.   Since we need to both be forward looking but backwards compatible, there is additional logic for revenue events.  Non revenue events are not impacted by the `$` prefix:
*  For Amplitude revenue events, when `excludeIndividualProductEvents` = true, we send a single summary event and need to prefix `price` and `revenue` with a `$` so that Amplitude knows to use these values.
* * When `excludeIndividualProductEvents` = false, we support Scenario B, and we need to remove the `$` from `price` and `revenue` from the summary event, and send the traditional revenue event via the `logRevenueV2`, which will automatically append the `$`. We avoid manually appending `$` in the summary event in this case to avoid Amplitude double counting.

Finally, Amplitude requests that we append a key `mparticle_amplitude_should_split` so their servers know that this update has been made.

## Testing Plan
Updated ecommerce unit tests which failed due to the changing ecommerce mappings.  Added tests for revenue and non revenue events for when the flag `excludeIndividualProductEvents` is `true`, and `false`.

## Reference Issue
- Closes https://go.mparticle.com/work/SQDSDKS-4388

2022-08-24 16:17 UTC, alexs-mparticle requested changes

2022-08-25 15:39 UTC, alexs-mparticle requested changes

2022-08-25 15:39 UTC, alexs-mparticle commented on src/Amplitude.js
> +            if (key !== TOTAL_AMOUNT && key !== 'Total Product Amount') {
You missed `TOTAL_PRODUCT_AMOUNT`

2022-08-25 15:39 UTC, alexs-mparticle commented on src/Amplitude.js
> +            return wasProcessed;
```suggestion
            return processProductAction(event, expandedEvents);
```

2022-08-25 15:39 UTC, alexs-mparticle commented on src/Amplitude.js
> +            'Commerce event does not conform to our expectations and was not forwarded to Amplitude. Please double check your code.'
```suggestion
            'Commerce event does not conform to our expectations and was not forwarded to Amplitude. Please double-check your code.'
```

2022-08-25 15:39 UTC, alexs-mparticle commented on src/Amplitude.js
> +};;
```suggestion
};
```

2022-08-25 15:43 UTC, rmi22186 commented on src/Amplitude.js
> +            'Commerce event does not conform to our expectations and was not forwarded to Amplitude. Please double check your code.'
TIL there's a hyphen.

2022-08-25 18:29 UTC, rmi22186 commented on src/Amplitude.js
> +    function processProductAction(unexpandedCommerceEvent, expandedEvents) {
i added a .MD file in the test folder to show this.  I think as a comment might be a little too big.  so i referenced it there too.

2022-08-25 18:37 UTC, alexs-mparticle commented on test/AmplitudeCommerceEvents.MD
> +## Revenue Commerce Events (purchases and refunds)
I think this file should be under a `/docs` folder

2022-08-25 19:27 UTC, alexs-mparticle approved these changes

2022-08-25 19:29 UTC, merged